In [18]:
#Sorting Single 1-D Array
import numpy as np
a1=np.array([1,2,3,4,5])
print(np.sort(a1))

#Sorting 2-D Array
# a2=np.array([[1,5,3], [2,5,7], [400, 200, 300]])
# a3=np.sort(a2)
# print(a3)
# print("Search 2-D Array Elements Column-Wise")
# print(np.sort(a2,axis=0))
# print("Search 2-D Array Elements Row-Wise")
# print(np.sort(a2,axis=1))

a2=np.array([[1,6,8],[3,2,7],[9,4,5]])
print(np.sort(a2))
print("Column-Wise")
print(np.sort(a2,axis=0))
print("Row-Wise")
print(np.sort(a2,axis=1))


[1 2 3 4 5]
[[1 6 8]
 [2 3 7]
 [4 5 9]]
Column-Wise
[[1 2 5]
 [3 4 7]
 [9 6 8]]
Row-Wise
[[1 6 8]
 [2 3 7]
 [4 5 9]]


In [28]:
#BroadCasting
#Case1:if both matrices dimensions are same then element wise addition is possible
a3=np.tile(np.arange(0,4),(3,1))
print(a3)
#Transpose of a matrix
a4=a3.T
print(a4)
a5=np.tile(np.arange(4,8,1),(3,1))
print(a5)
print(a3+a5)


[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
[[ 4  6  8 10]
 [ 4  6  8 10]
 [ 4  6  8 10]]


In [34]:
#Case2:Right array should be of 1-D and columns should match with the other matrix
a6=np.tile(np.arange(1,4,1),(3,1))
print(a6)
a7=np.tile(np.arange(1,4),(1,1))

print(a6+a7)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[2 4 6]
 [2 4 6]
 [2 4 6]]
