In [3]:
#Hello {Name}
Name=input("")
print(f"Hello {Name}")

Vijay
Hello Vijay


In [5]:
a=-1
b=-1
c=+2

x=a<b+c
print(x)

True


In [11]:
print(True==1)
print(True)
print(1=='1')
print(55/11)
print(55//11)

True
True
False
5.0
5


In [12]:
A=int(input("enter A"))
B=int(input("enter B"))
if(A<B):
    print(A)
else:
    print(B)

enter A10
enter B20
10


In [15]:
x=int(input("enter X"))
if x>2:
    x=x*2
print(x)
if x>4:
    x=0
print(x)

enter X3
6
0


Creating Numpy DataType

In [14]:

import numpy as np
#one-d array
arr=np.array([1,2,4,5])
print(type(arr))
print(arr.ndim)
#Two-d array
arr2=np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)
print(arr2.ndim)
print(type(arr2))
print(arr2[1,3])
arr3=np.array([1,2,3],ndmin=3)
print(arr3)
print(arr3.ndim)


<class 'numpy.ndarray'>
1
[[1 2 3 4]
 [2 3 4 5]]
2
<class 'numpy.ndarray'>
[[[1 2 3]]]
3
5


#Slicing Operation

In [18]:
#Slicing
a=np.array([1,2,3,4,5])
print(a[1:4])
#Every other item from (including) the second item to (not including) the fifth item.
#Tip: use the step syntax.
print(a[1:4:2])




[2 3 4]
[2 4]


DataTypes in Numpy

In [24]:
#Convert b array integers to String
b=np.array([1,2,3,4],dtype='S')
print(b)
#Convert float values to intger
c=np.array([1.1,2.2,3.3,4.4])
print(c.astype('i'))




[b'1' b'2' b'3' b'4']
[1 2 3 4]


#Copying the array elements

In [27]:
d=np.array([1,2,3,4])
e=d.copy()
print(e)
#View of the array
f=d.view()
print(f)

[1 2 3 4]
[1 2 3 4]


Shape and reshape of an array

In [37]:
arr=np.array([1,2,3,4])
print(arr.shape)
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("actual shape",arr1.shape)
print(arr1)
arr2=arr1.reshape(4,3)
print("rearranged shape",arr2.shape)
print(arr2.reshape(3,4))

#Change shape of an array from 2-D to 1-D
arr3=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr3.reshape(-1))

(4,)
actual shape (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
rearranged shape (4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 20 30 40 50 60 70 80 90]


Join Operation on numpy arrays

In [44]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
c=np.array([2,34,55])
print(np.concatenate((a,b)))
print(np.concatenate((a,c)))

[1 2 3 4 4 5 6 7]
[ 1  2  3  4  2 34 55]


#Searching  and Sorting

In [53]:
x=np.where(a==4)
print(x)
y=np.where(b==4)
print(y)
z=np.where(c==4)
print(z)

sort_ele=np.sort(a)
print(sort_ele)


(array([3], dtype=int64),)
(array([0], dtype=int64),)
(array([], dtype=int64),)
[1 2 3 4]


In [60]:
#time comparision with numpy and array
arr1=np.array([1,2,3,4])
res=[(j**2) for j in arr1]
print(res)
%timeit res

#time Comparision blw them
l=range(100000)
%timeit [i**2 for i in l]

l1=np.array(range(100000))
%timeit l1**2


[1, 4, 9, 16]
16.1 ns ± 0.956 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
7.56 ms ± 485 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
50.8 µs ± 4.63 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
